version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-name: "actions/*"
      - dependency-name: "redhat-actions/*"
