pluginManagement {
	plugins {
		id "org.checkerframework" version "1.0.2" apply false
	}
	repositories {
		gradlePluginPortal()
		mavenCentral()
	}
}

plugins {
	id 'com.gradle.develocity' version '4.5.0'
}

rootProject.name = "hibernate-models-group"

dependencyResolutionManagement {
	repositories {
		mavenCentral()
		if (rootProject.hasProperty("enableSnapshotRepositories")) {
			maven {
				// temporary - Maven Central snapshots repo for ORM snapshots
				url = "https://central.sonatype.com/repository/maven-snapshots/"
				mavenContent {
					snapshotsOnly()
				}
			}
		}
		// Needed for RC versions of Jakarta Persistence
		maven {
			url = "https://jakarta.oss.sonatype.org/content/repositories/releases/"
		}
		// Needed for Beta versions of Jakarta Persistence
		maven {
			url = "https://jakarta.oss.sonatype.org/content/groups/staging/"
		}
		if (rootProject.hasProperty("enableSnapshotRepositories")) {
			// Needed for SNAPSHOT versions of Jakarta Persistence (wtf)
			maven {
				url = "https://jakarta.oss.sonatype.org/content/repositories/snapshots/"
			}
		}
	}
}

develocity {
	server = 'https://develocity.commonhaus.dev'

	buildScan {
		capture {
			fileFingerprints = true
		}
		publishing.onlyIf { it.authenticated }

		obfuscation {
			// Don't share ip addresses
			ipAddresses { addresses -> addresses.collect { address -> "0.0.0.0" } }
		}

//			uploadInBackground = !settings.ext.isCiEnvironment
//
//			tag "jdk-${settings.extensions.jdkVersions.test.launcher}"
//			tag settings.extensions.db
//			value 'database', settings.extensions.db
//
//			if ( settings.extensions.findByName( 'ci.node' ) ) {
//				tag settings.extensions.findByName( 'ci.node' )
//			}
	}
}

include "hibernate-models"
include "hibernate-models-jandex"
include 'hibernate-models-bytebuddy'
include 'hibernate-models-testing'
include 'reporting'

include 'hibernate-models-accessor'
project(':hibernate-models-accessor').projectDir = file('hibernate-models-accessor/hibernate-models-accessor')

include 'hibernate-models-accessor-asm'
project(':hibernate-models-accessor-asm').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-asm')

include 'hibernate-models-accessor-tck'
project(':hibernate-models-accessor-tck').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-tck')

include 'hibernate-models-accessor-tck-reflection'
project(':hibernate-models-accessor-tck-reflection').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-tck-reflection')

include 'hibernate-models-accessor-tck-methodhandle'
project(':hibernate-models-accessor-tck-methodhandle').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-tck-methodhandle')

include 'hibernate-models-accessor-tck-lambda'
project(':hibernate-models-accessor-tck-lambda').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-tck-lambda')

include 'hibernate-models-accessor-tck-asm'
project(':hibernate-models-accessor-tck-asm').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-tck-asm')

include 'hibernate-models-accessor-bytebuddy'
project(':hibernate-models-accessor-bytebuddy').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-bytebuddy')

include 'hibernate-models-accessor-tck-bytebuddy'
project(':hibernate-models-accessor-tck-bytebuddy').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-tck-bytebuddy')

include 'hibernate-models-accessor-generator'
project(':hibernate-models-accessor-generator').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-generator')

include 'hibernate-models-accessor-tck-generator'
project(':hibernate-models-accessor-tck-generator').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-tck-generator')

include 'hibernate-models-accessor-tck-jpms-entities'
project(':hibernate-models-accessor-tck-jpms-entities').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-tck-jpms-entities')

include 'hibernate-models-accessor-tck-jpms'
project(':hibernate-models-accessor-tck-jpms').projectDir = file('hibernate-models-accessor/hibernate-models-accessor-tck-jpms')
