sonar.host.url=https://sonarcloud.io
sonar.organization=hibernate
sonar.projectKey=hibernate_hibernate-models
sonar.projectName=Hibernate Models
sonar.projectDescription=An abstraction over \"reflection\" and annotations.

sonar.language=java
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main

sonar.modules=hibernate-models,hibernate-models-bytebuddy,hibernate-models-jandex

hibernate-models.sonar.projectName=Hibernate Models - Core
hibernate-models.sonar.projectBaseDir=hibernate-models

hibernate-models-bytebuddy.sonar.projectName=Hibernate Models - ByteBuddy
hibernate-models-bytebuddy.sonar.projectBaseDir=hibernate-models-bytebuddy

hibernate-models-jandex.sonar.projectName=Hibernate Models - Jandex
hibernate-models-jandex.sonar.projectBaseDir=hibernate-models-jandex
