plugins {
    id 'jacoco-report-aggregation'
}

description = 'Reporting module'

dependencies {
    jacocoAggregation project(':hibernate-models')
    jacocoAggregation project(':hibernate-models-bytebuddy')
    jacocoAggregation project(':hibernate-models-jandex')
    jacocoAggregation project(':hibernate-models-accessor')
    jacocoAggregation project(':hibernate-models-accessor-asm')
    jacocoAggregation project(':hibernate-models-accessor-bytebuddy')
}

tasks.register('mergeCodeCoverageReport', JacocoReport) {
    executionData fileTree(rootProject.layout.projectDirectory.asFile).include("**/build/jacoco/*.exec")
    sourceSets project(':hibernate-models').sourceSets.main
    sourceSets project(':hibernate-models-bytebuddy').sourceSets.main
    sourceSets project(':hibernate-models-jandex').sourceSets.main
    sourceSets project(':hibernate-models-accessor').sourceSets.main
    sourceSets project(':hibernate-models-accessor-asm').sourceSets.main
    sourceSets project(':hibernate-models-accessor-bytebuddy').sourceSets.main

    reports {
        xml.required = true
    }

    dependsOn rootProject.subprojects.collect { p -> p.tasks.matching { it.name == 'compileJava' } }
}
